/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sap_aq3d;


import com.mysql.jdbc.PreparedStatement;
import java.sql.SQLException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Max
 */
public class regchar extends javax.swing.JFrame {
    /**
     * Creates new form regchar
     */
    public regchar() {
        initComponents();
    }
    public void clearTextField(){
        name.setText("");
        lvl.setText("");
        classRank.setText("");
        health.setText("");
        atk.setText("");
        armor.setText("");
        crit.setText("");
        eva.setText("");
        haste.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lvl = new javax.swing.JTextField();
        classRank = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        health = new javax.swing.JTextField();
        atk = new javax.swing.JTextField();
        crit = new javax.swing.JTextField();
        armor = new javax.swing.JTextField();
        eva = new javax.swing.JTextField();
        haste = new javax.swing.JTextField();
        proceed = new javax.swing.JButton();
        back = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        memList = new javax.swing.JMenuItem();
        charList = new javax.swing.JMenuItem();
        regChar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 400));
        setPreferredSize(new java.awt.Dimension(420, 400));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Character Register");

        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("Name");

        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("Max Health");

        jLabel4.setForeground(new java.awt.Color(204, 0, 204));
        jLabel4.setText("Attack");

        jLabel5.setForeground(new java.awt.Color(204, 0, 204));
        jLabel5.setText("Level");

        jLabel6.setForeground(new java.awt.Color(204, 0, 204));
        jLabel6.setText("Total Class Rank");

        jLabel7.setForeground(new java.awt.Color(204, 0, 204));
        jLabel7.setText("Armor");

        jLabel8.setForeground(new java.awt.Color(204, 0, 204));
        jLabel8.setText("Crit");

        jLabel9.setForeground(new java.awt.Color(204, 0, 204));
        jLabel9.setText("Evasion");

        jLabel10.setForeground(new java.awt.Color(204, 0, 204));
        jLabel10.setText("Haste");

        atk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atkActionPerformed(evt);
            }
        });

        eva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaActionPerformed(evt);
            }
        });

        haste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasteActionPerformed(evt);
            }
        });

        proceed.setBackground(new java.awt.Color(153, 0, 153));
        proceed.setForeground(new java.awt.Color(255, 255, 255));
        proceed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tick.png"))); // NOI18N
        proceed.setText("Proceed");
        proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(153, 0, 153));
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/left-arrow.png"))); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(153, 0, 153));
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear-button.png"))); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        menu.setText("Menu");

        memList.setText("Member List");
        memList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memListActionPerformed(evt);
            }
        });
        menu.add(memList);

        charList.setText("Character List");
        charList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charListActionPerformed(evt);
            }
        });
        menu.add(charList);

        regChar.setText("Register Character");
        regChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regCharActionPerformed(evt);
            }
        });
        menu.add(regChar);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5)
                        .addGap(15, 15, 15)
                        .addComponent(lvl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6)
                        .addGap(9, 9, 9)
                        .addComponent(classRank, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(health, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(atk, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(armor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel8)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel9)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(crit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(eva, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(haste, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(proceed)
                        .addGap(19, 19, 19)
                        .addComponent(clear)
                        .addGap(21, 21, 21)
                        .addComponent(back))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(classRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(lvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(health, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(armor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(haste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(proceed)
                    .addComponent(clear)
                    .addComponent(back)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void evaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evaActionPerformed

    private void hasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasteActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new fhome().setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void atkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atkActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        clearTextField();
    }//GEN-LAST:event_clearActionPerformed

    private void memListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memListActionPerformed
        try {
            new memlist().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(regchar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_memListActionPerformed

    private void charListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charListActionPerformed
        try {
            new charlist().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(regchar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_charListActionPerformed

    private void regCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regCharActionPerformed
        
    }//GEN-LAST:event_regCharActionPerformed

    private void proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedActionPerformed
        String query="INSERT INTO `karakter`(`id_mem`,`name`,`level`,`classrank`,`health`,`atk`,`armor`,`crit`,`eva`,`haste`) VALUES(?,?,?,?,?,?,?,?,?,?)";
        //System.out.println(mainlogin.getUser());
        try{
            PreparedStatement ps = (PreparedStatement) DBConnection.getConnection().prepareStatement(query);
            ps.setInt(1, Integer.parseInt(mainlogin.getUser()));
            ps.setString(2, name.getText());
            ps.setInt(3, Integer.parseInt(lvl.getText()));
            ps.setInt(4, Integer.parseInt(classRank.getText()));
            ps.setInt(5, Integer.parseInt(health.getText()));
            ps.setInt(6, Integer.parseInt(atk.getText()));
            ps.setInt(7, Integer.parseInt(armor.getText()));
            ps.setInt(8, Integer.parseInt(crit.getText()));
            ps.setInt(9, Integer.parseInt(eva.getText()));
            ps.setInt(10, Integer.parseInt(haste.getText()));
            if(ps.executeUpdate()>0){
                JOptionPane.showMessageDialog(null, "New char added!");
                new fhome().setVisible(true);
                this.dispose();
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Char not saved!");
        }
    }//GEN-LAST:event_proceedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regchar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regchar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regchar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regchar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regchar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField armor;
    private javax.swing.JTextField atk;
    private javax.swing.JButton back;
    private javax.swing.JMenuItem charList;
    private javax.swing.JTextField classRank;
    private javax.swing.JButton clear;
    private javax.swing.JTextField crit;
    private javax.swing.JTextField eva;
    private javax.swing.JTextField haste;
    private javax.swing.JTextField health;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField lvl;
    private javax.swing.JMenuItem memList;
    private javax.swing.JMenu menu;
    private javax.swing.JTextField name;
    private javax.swing.JButton proceed;
    private javax.swing.JMenuItem regChar;
    // End of variables declaration//GEN-END:variables
}
